# coding: utf-8

"""
    Mozart API

    API for HySDS job submission and query.  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import hysds.mozart.client
from hysds.mozart.client.api.queue_api import QueueApi  # noqa: E501
from hysds.mozart.client.rest import ApiException


class TestQueueApi(unittest.TestCase):
    """QueueApi unit test stubs"""

    def setUp(self):
        self.api = hysds.mozart.client.api.queue_api.QueueApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_get_queue_names(self):
        """Test case for get_get_queue_names

        Gets a listing of non-celery queues handling jobs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
