# coding: utf-8

"""
    Mozart API

    API for HySDS job submission and query.  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import hysds.mozart.client
from hysds.mozart.client.api.container_api import ContainerApi  # noqa: E501
from hysds.mozart.client.rest import ApiException


class TestContainerApi(unittest.TestCase):
    """ContainerApi unit test stubs"""

    def setUp(self):
        self.api = hysds.mozart.client.api.container_api.ContainerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_get_container_info(self):
        """Test case for get_get_container_info

        Get information on container by ID  # noqa: E501
        """
        pass

    def test_get_get_container_remove(self):
        """Test case for get_get_container_remove

        Remove container based on ID  # noqa: E501
        """
        pass

    def test_get_get_container_types(self):
        """Test case for get_get_container_types

        Get a list of containers managed by Mozart  # noqa: E501
        """
        pass

    def test_post_get_container_add(self):
        """Test case for post_get_container_add

        Add a container specification to Mozart  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
