# coding: utf-8

"""
    Mozart API

    API for HySDS job submission and query.  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import hysds.mozart.client
from hysds.mozart.client.models.container_info_response_json import ContainerInfoResponseJSON  # noqa: E501
from hysds.mozart.client.rest import ApiException

class TestContainerInfoResponseJSON(unittest.TestCase):
    """ContainerInfoResponseJSON unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ContainerInfoResponseJSON
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = hysds.mozart.client.models.container_info_response_json.ContainerInfoResponseJSON()  # noqa: E501
        if include_optional :
            return ContainerInfoResponseJSON(
                success = True, 
                message = '0', 
                result = None
            )
        else :
            return ContainerInfoResponseJSON(
                success = True,
                message = '0',
                result = None,
        )

    def testContainerInfoResponseJSON(self):
        """Test ContainerInfoResponseJSON"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
