# coding: utf-8

"""
    Mozart API

    API for HySDS job submission and query.  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import hysds.mozart.client
from hysds.mozart.client.models.hy_sdsio_addition_response_json import HySDSIOAdditionResponseJSON  # noqa: E501
from hysds.mozart.client.rest import ApiException

class TestHySDSIOAdditionResponseJSON(unittest.TestCase):
    """HySDSIOAdditionResponseJSON unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test HySDSIOAdditionResponseJSON
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = hysds.mozart.client.models.hy_sdsio_addition_response_json.HySDSIOAdditionResponseJSON()  # noqa: E501
        if include_optional :
            return HySDSIOAdditionResponseJSON(
                success = True, 
                message = '0', 
                result = '0'
            )
        else :
            return HySDSIOAdditionResponseJSON(
                success = True,
                message = '0',
                result = '0',
        )

    def testHySDSIOAdditionResponseJSON(self):
        """Test HySDSIOAdditionResponseJSON"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
