# coding: utf-8

"""
    Mozart API

    API for HySDS job submission and query.  # noqa: E501

    The version of the OpenAPI document: 0.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import hysds.mozart.client
from hysds.mozart.client.api.job_api import JobApi  # noqa: E501
from hysds.mozart.client.rest import ApiException


class TestJobApi(unittest.TestCase):
    """JobApi unit test stubs"""

    def setUp(self):
        self.api = hysds.mozart.client.api.job_api.JobApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_get_job_info(self):
        """Test case for get_get_job_info

        Get complete infor on submitted job based on id  # noqa: E501
        """
        pass

    def test_get_get_job_status(self):
        """Test case for get_get_job_status

        Gets the status of a submitted job based on job id  # noqa: E501
        """
        pass

    def test_get_get_jobs(self):
        """Test case for get_get_jobs

        Paginated list submitted jobs  # noqa: E501
        """
        pass

    def test_post_submit_job(self):
        """Test case for post_submit_job

        Submits a job to run inside HySDS  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
